[package]
name = "step2"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2018"

[dependencies]
fast-float = "0.2"
memchr = "2.4.0"
nom = "6.0"
rayon = "1.5"

[dev-dependencies]
clap = "2.33"
